name: Build

on:
  push:
    tags:
      - 'EModelRunner-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  call-test-workflow:
    uses: BlueBrain/EModelRunner/.github/workflows/test.yml@main

  test-ref:
    if: github.ref == 'refs/heads/main'
    name: test ref
    runs-on: ubuntu-latest
    steps:
      - run: echo "Passed ref test"
      
  test-needs:
    name: test needs
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - run: echo "Passed needs test"

  build-n-publish:
    if: github.ref == 'refs/heads/main'
    name: Build and publish on PyPI
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - run: echo "Passed needs and ref test"
